name: medmnist
channels:
  - conda-forge
  - defaults
dependencies:
  # Base depends
  - python
  - pip

  # Repo
  - pytorch==1.3.1
  - tensorflow==2.3.0
  - ASConv
  
  # secret dependencies
  - tensorboardX
  
  - pip:
    - medmnist
    - autokeras==1.0.15
    - auto-sklearn==0.10.0